# Generated by Django 2.0.2 on 2018-06-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='emergency',
            new_name='emergency_contact',
        ),
    ]
