# Generated by Django 2.0.2 on 2018-06-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180610_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='exact_item_required',
        ),
        migrations.AlterField(
            model_name='preference',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item'),
        ),
    ]
